<script setup lang="ts">
import { computed, ref } from 'vue'
import { onShow } from '@dcloudio/uni-app'
import { connect, disconnect, reconnect, saveSettings, store } from '@/services/relay'
import {
  accessibility,
  setSimpleMode,
  setTextScale,
  textScaleClass,
  type TextScale,
} from '@/services/accessibility'
import { describePairingDiagnostics, type RelayPairDiagnostics } from '@/services/diagnostics'
import { mobileRelayUrlToHttpBase, normalizeMobileRelayUrl, parsePairPayload } from '@/services/pairing'
import type { ConnectionStatus } from '@/services/protocol'

const draftUrl = ref(store.relayUrl || normalizeMobileRelayUrl(''))
const draftToken = ref(store.pairToken)
const draftDeviceName = ref(store.deviceName || '我的手机')
const autoGeneratedToken = ref('')
const diagnosisTitle = ref('')
const diagnosisDetail = ref('')
const isPairing = ref(false)
const isDiagnosing = ref(false)
const showAdvanced = ref(false)
const showToken = ref(false)
const showTechnical = ref(false)
const isConnecting = computed(() => store.connectionStatus === 'connecting')

onShow(() => {
  if (store.relayUrl) draftUrl.value = store.relayUrl
  if (store.pairToken) draftToken.value = store.pairToken
  if (store.deviceName) draftDeviceName.value = store.deviceName
})

const statusTitle = computed(() => ({
  idle: '尚未配对',
  connecting: '正在连接',
  connected: '同步已连接',
  disconnected: '连接已中断',
  'auth-failed': '配对已失效',
} satisfies Record<ConnectionStatus, string>)[store.connectionStatus])

const statusDescription = computed(() => {
  if (store.lastError) return store.lastError
  if (store.connectionStatus === 'connected') {
    return store.workspaces.length
      ? `${store.workspaces.length} 个工作区正在同步`
      : 'relay 已连接，等待 Windows 端发送数据'
  }
  if (store.connectionStatus === 'connecting') return '正在恢复与 relay 的连接'
  if (store.connectionStatus === 'disconnected') return '检查网络后重连，配对信息不会丢失'
  if (store.connectionStatus === 'auth-failed') return '重新扫描 Windows 端二维码以恢复配对'
  return '扫描 Windows 端二维码即可开始同步'
})

function onConnect() {
  const url = normalizeMobileRelayUrl(draftUrl.value)
  const token = draftToken.value.trim()
  const name = draftDeviceName.value.trim() || 'pi-mobile'
  if (!url || !token) {
    uni.showToast({ title: '请填写服务器地址和 Token', icon: 'none' })
    return
  }
  draftUrl.value = url
  saveSettings(url, token, name)
  connect(url, token, name)
}

function onDisconnect() {
  disconnect()
}

function onReconnect() {
  if (!store.pairToken && draftToken.value.trim()) {
    onConnect()
    return
  }
  reconnect()
}

async function onScanQR() {
  try {
    const res = await uni.scanCode({ onlyFromCamera: true, scanType: ['qrCode'] })
    applyPairPayload(res.result || '')
    onConnect()
  } catch (error) {
    const message = typeof (error as { errMsg?: unknown })?.errMsg === 'string'
      ? (error as { errMsg: string }).errMsg
      : '请检查相机权限，或使用手动连接'
    if (!message.includes('cancel')) {
      uni.showToast({ title: `扫码失败：${message}`, icon: 'none', duration: 3200 })
    }
  }
}

function createPairToken(apiUrl: string, label: string): Promise<string> {
  return new Promise((resolve, reject) => {
    uni.request({
      url: `${apiUrl}/api/pair/create`,
      method: 'POST',
      header: { 'content-type': 'application/json' },
      data: { label },
      success(res) {
        if (res.statusCode < 200 || res.statusCode >= 300) return reject(new Error(`HTTP ${res.statusCode}`))
        const data = res.data as { pairToken?: string }
        if (!data?.pairToken) return reject(new Error('服务器没有返回 Token'))
        resolve(data.pairToken)
      },
      fail(error) { reject(new Error(error.errMsg || '请求失败')) },
    })
  })
}

function requestPairDiagnostics(apiUrl: string, pairToken: string): Promise<RelayPairDiagnostics> {
  return new Promise((resolve, reject) => {
    uni.request({
      url: `${apiUrl}/api/pair/diagnostics`,
      method: 'POST',
      header: { 'content-type': 'application/json' },
      data: { pairToken },
      success(res) {
        if (res.statusCode < 200 || res.statusCode >= 300) return reject(new Error(`HTTP ${res.statusCode}`))
        resolve(res.data as RelayPairDiagnostics)
      },
      fail(error) { reject(new Error(error.errMsg || '请求失败')) },
    })
  })
}

async function onAutoPair() {
  const relayUrl = normalizeMobileRelayUrl(draftUrl.value)
  if (!relayUrl) return
  isPairing.value = true
  autoGeneratedToken.value = ''
  try {
    const pairToken = await createPairToken(mobileRelayUrlToHttpBase(relayUrl), draftDeviceName.value.trim() || 'phone')
    draftUrl.value = relayUrl
    draftToken.value = pairToken
    autoGeneratedToken.value = pairToken
    saveSettings(relayUrl, pairToken, draftDeviceName.value.trim() || 'phone')
    connect(relayUrl, pairToken, draftDeviceName.value.trim() || 'phone')
    uni.showToast({ title: 'Token 已生成，请粘贴到 Windows 端', icon: 'none', duration: 3000 })
  } catch (error) {
    uni.showToast({ title: `生成失败：${error instanceof Error ? error.message : String(error)}`, icon: 'none', duration: 3000 })
  } finally {
    isPairing.value = false
  }
}

async function onDiagnose() {
  const relayUrl = normalizeMobileRelayUrl(draftUrl.value)
  const token = draftToken.value.trim()
  if (!token) {
    uni.showToast({ title: '请先填写 Token', icon: 'none' })
    return
  }
  isDiagnosing.value = true
  diagnosisTitle.value = ''
  diagnosisDetail.value = ''
  try {
    const diagnostics = await requestPairDiagnostics(mobileRelayUrlToHttpBase(relayUrl), token)
    const diagnosis = describePairingDiagnostics(diagnostics)
    diagnosisTitle.value = diagnosis.title
    diagnosisDetail.value = diagnosis.detail
  } catch (error) {
    diagnosisTitle.value = '诊断失败'
    diagnosisDetail.value = error instanceof Error ? error.message : String(error)
  } finally {
    isDiagnosing.value = false
  }
}

function applyPairPayload(result: string) {
  const parsed = parsePairPayload(result)
  if (parsed.relayUrl) draftUrl.value = parsed.relayUrl
  if (parsed.pairToken) draftToken.value = parsed.pairToken
}

function copyToken() {
  const token = draftToken.value.trim()
  if (token) uni.setClipboardData({ data: token })
}

function onTextScaleChange(scale: TextScale) {
  setTextScale(scale)
}

function onSimpleModeChange(event: Event) {
  const value = Boolean((event as Event & { detail?: { value?: boolean } }).detail?.value)
  setSimpleMode(value)
  if (!value) showTechnical.value = false
}
</script>

<template>
  <view :class="['settings-page', textScaleClass, { 'simple-mode': accessibility.simpleMode }]">
    <view class="app-safe-top page-header">
      <view class="header-row">
        <view>
          <text class="page-title">设置</text>
          <text class="header-meta">移动同步 · v1.0.6</text>
        </view>
      </view>
    </view>

    <scroll-view class="settings-scroll" scroll-y :show-scrollbar="false">
      <view :class="['status-panel', `status-panel--${store.connectionStatus}`]">
        <view class="status-icon">
          <image src="/static/icon-wifi.png" mode="aspectFit" />
        </view>
        <view class="status-main">
          <text class="status-title">{{ statusTitle }}</text>
          <text class="status-description">{{ statusDescription }}</text>
        </view>
        <text class="status-dot" />
      </view>

      <view class="primary-actions">
        <button class="scan-button" @tap="onScanQR">
          <image src="/static/icon-qr-code.png" mode="aspectFit" />
          <view class="scan-copy">
            <text class="scan-title">扫描 Windows 配对码</text>
            <text class="scan-subtitle">推荐方式，扫码后自动连接</text>
          </view>
          <image class="scan-chevron" src="/static/icon-chevron-down.png" mode="aspectFit" />
        </button>
      </view>

      <view class="section-block accessibility-block">
        <text class="section-label">显示与易用性</text>
        <view class="settings-list">
          <view class="accessibility-row accessibility-row--size">
            <view>
              <text class="accessibility-title">字体大小</text>
            </view>
            <view class="text-size-control">
              <button :class="accessibility.textScale === 'standard' ? 'is-active' : ''" @tap="onTextScaleChange('standard')">标准</button>
              <button :class="accessibility.textScale === 'large' ? 'is-active' : ''" @tap="onTextScaleChange('large')">大字</button>
              <button :class="accessibility.textScale === 'extra-large' ? 'is-active' : ''" @tap="onTextScaleChange('extra-large')">特大</button>
            </view>
          </view>
          <view class="accessibility-row">
            <view>
              <text class="accessibility-title">简洁模式</text>
            </view>
            <switch :checked="accessibility.simpleMode" color="#17191c" @change="onSimpleModeChange" />
          </view>
        </view>
      </view>

      <view v-if="accessibility.simpleMode && !showTechnical" class="section-block">
        <button class="technical-toggle" @tap="showTechnical = true">
          <text>高级设置</text>
          <image src="/static/icon-chevron-down.png" mode="aspectFit" />
        </button>
      </view>

      <view v-if="!accessibility.simpleMode || showTechnical" class="technical-settings">
      <view class="section-block">
        <text class="section-label">连接</text>
        <view class="settings-list">
          <view class="field-row">
            <view class="field-label-wrap">
              <image src="/static/icon-link-2.png" mode="aspectFit" />
              <text class="field-label">服务器</text>
            </view>
            <input v-model="draftUrl" class="field-input" placeholder="ws://服务器/ws/mobile" />
          </view>
          <view class="field-row">
            <view class="field-label-wrap">
              <image src="/static/icon-copy.png" mode="aspectFit" />
              <text class="field-label">Token</text>
            </view>
            <input v-model="draftToken" class="field-input" :password="!showToken" placeholder="pi_xxx" />
            <button class="small-action" @tap="showToken = !showToken">{{ showToken ? '隐藏' : '显示' }}</button>
            <button class="small-action" :disabled="!draftToken" @tap="copyToken">复制</button>
          </view>
          <view class="field-row">
            <view class="field-label-wrap">
              <image src="/static/tab-settings.png" mode="aspectFit" />
              <text class="field-label">设备名</text>
            </view>
            <input v-model="draftDeviceName" class="field-input" placeholder="我的手机" />
          </view>
        </view>
        <view class="connection-actions">
          <button class="primary-button" :disabled="isConnecting" @tap="onConnect">{{ isConnecting ? '连接中…' : '保存并连接' }}</button>
          <button class="secondary-button" @tap="onReconnect">重连</button>
          <button class="danger-button" @tap="onDisconnect">断开</button>
        </view>
      </view>

      <view class="section-block">
        <text class="section-label">诊断</text>
        <view class="settings-list">
          <view class="diagnostic-row">
            <view>
              <text class="diagnostic-title">连接诊断</text>
              <text class="diagnostic-subtitle">检查桌面在线、手机在线和快照状态</text>
            </view>
            <button class="diagnostic-button" :disabled="isDiagnosing" @tap="onDiagnose">{{ isDiagnosing ? '检查中' : '诊断同步' }}</button>
          </view>
          <view v-if="diagnosisTitle" class="diagnosis-result">
            <text class="diagnosis-title">{{ diagnosisTitle }}</text>
            <text class="diagnosis-detail">{{ diagnosisDetail }}</text>
          </view>
        </view>
      </view>

      <view class="section-block">
        <button class="advanced-toggle" @tap="showAdvanced = !showAdvanced">
          <text>其它配对方式与协议信息</text>
          <image :class="showAdvanced ? 'is-open' : ''" src="/static/icon-chevron-down.png" mode="aspectFit" />
        </button>
        <view v-if="showAdvanced" class="advanced-content">
          <button class="secondary-button full-button" :disabled="isPairing" @tap="onAutoPair">{{ isPairing ? '生成中…' : '在手机生成 Token' }}</button>
          <view v-if="autoGeneratedToken" class="generated-token" @tap="copyToken">
            <text class="generated-label">点按复制，然后粘贴到 Windows 端</text>
            <text class="generated-value">{{ autoGeneratedToken }}</text>
          </view>
          <view class="protocol-list">
            <view><text>手机端</text><text>/ws/mobile</text></view>
            <view><text>Windows 端</text><text>/ws/desktop</text></view>
            <view><text>配对规则</text><text>两端 Token 完全一致</text></view>
          </view>
        </view>
      </view>
      <button v-if="accessibility.simpleMode" class="collapse-technical" @tap="showTechnical = false">收起高级设置</button>
      </view>
      <view class="scroll-spacer" />
    </scroll-view>
  </view>
</template>

<style scoped>
.settings-page { height: 100vh; display: flex; flex-direction: column; background: #f5f6f8; color: #17191c; }
.page-header { flex-shrink: 0; background: #fff; border-bottom: 1rpx solid #e7e9ed; }
.header-row { min-height: var(--app-header-height, 112rpx); padding: 16rpx 24rpx; display: flex; align-items: center; }
.page-title { display: block; font-size: var(--font-page-title, 40rpx); line-height: 1.2; font-weight: 760; }
.header-meta { display: block; margin-top: 4rpx; color: #777d86; font-size: var(--font-meta, 23rpx); }
.settings-scroll { flex: 1; min-height: 0; }
.status-panel { min-height: 116rpx; margin: 20rpx 20rpx 0; padding: 20rpx; display: flex; align-items: center; gap: 18rpx; border-radius: 16rpx; background: #fff; border: 1rpx solid #e5e7ea; }
.status-icon { width: 68rpx; height: 68rpx; display: flex; align-items: center; justify-content: center; flex-shrink: 0; border-radius: 14rpx; background: #eceef1; }
.status-icon image { width: 34rpx; height: 34rpx; }
.status-main { flex: 1; min-width: 0; }
.status-title { display: block; font-size: var(--font-title, 28rpx); font-weight: 700; }
.status-description { display: block; margin-top: 6rpx; overflow: hidden; color: #737983; font-size: var(--font-meta, 23rpx); line-height: 1.45; }
.status-dot { width: 16rpx; height: 16rpx; border-radius: 50%; flex-shrink: 0; background: #a5a9b0; }
.status-panel--connected .status-dot { background: #18a558; }
.status-panel--connecting .status-dot { background: #d98b0b; }
.status-panel--disconnected .status-dot,
.status-panel--auth-failed .status-dot { background: #d7463e; }
.primary-actions { margin-top: 20rpx; background: #fff; border-top: 1rpx solid #e7e9ed; border-bottom: 1rpx solid #e7e9ed; }
.scan-button { width: 100%; min-height: 112rpx; margin: 0; padding: 18rpx 24rpx; display: flex; align-items: center; gap: 18rpx; border: none; border-radius: 0; background: #fff; text-align: left; }
.scan-button > image:first-child { width: 44rpx; height: 44rpx; flex-shrink: 0; }
.scan-copy { flex: 1; min-width: 0; }
.scan-title { display: block; color: #1e2227; font-size: var(--font-title, 28rpx); font-weight: 680; }
.scan-subtitle { display: block; margin-top: 5rpx; color: #7a8089; font-size: var(--font-meta, 22rpx); }
.scan-chevron { width: 30rpx; height: 30rpx; transform: rotate(-90deg); }
.section-block { margin-top: 28rpx; }
.section-label { display: block; margin: 0 24rpx 12rpx; color: #717780; font-size: var(--font-meta, 23rpx); font-weight: 650; }
.settings-list { background: #fff; border-top: 1rpx solid #e7e9ed; border-bottom: 1rpx solid #e7e9ed; }
.accessibility-row { min-height: var(--app-control-height, 92rpx); margin-left: 24rpx; padding: 16rpx 24rpx 16rpx 0; display: flex; align-items: center; justify-content: space-between; gap: 18rpx; border-bottom: 1rpx solid #eceef1; }
.accessibility-row:last-child { border-bottom: none; }
.accessibility-row > view:first-child { flex-shrink: 0; }
.accessibility-title { display: block; color: #2d3239; font-size: var(--font-title, 27rpx); font-weight: 650; }
.text-size-control { flex: 1; min-width: 0; display: grid; grid-template-columns: repeat(3, 1fr); gap: 8rpx; padding: 6rpx; border-radius: 14rpx; background: #eceef1; }
.text-size-control button { min-width: 0; min-height: 62rpx; margin: 0; padding: 0 8rpx; border: none; border-radius: 10rpx; background: transparent; color: #626872; font-size: var(--font-meta, 22rpx); line-height: 1.2; }
.text-size-control button.is-active { background: #fff; color: #17191c; font-weight: 700; box-shadow: 0 2rpx 8rpx rgba(23, 25, 28, .1); }
.accessibility-row switch { transform: scale(1.08); transform-origin: right center; }
.technical-toggle { width: 100%; min-height: var(--app-control-height, 92rpx); margin: 0; padding: 0 24rpx; display: flex; align-items: center; justify-content: space-between; border: none; border-radius: 0; background: #fff; color: #30353c; font-size: var(--font-title, 27rpx); text-align: left; }
.technical-toggle image { width: 32rpx; height: 32rpx; transform: rotate(-90deg); }
.technical-settings { padding-bottom: 12rpx; }
.collapse-technical { width: calc(100% - 40rpx); min-height: 76rpx; margin: 20rpx; border: none; border-radius: 14rpx; background: #e8eaed; color: #4f555e; font-size: var(--font-body, 24rpx); line-height: 1.2; }
.field-row { min-height: 92rpx; margin-left: 24rpx; padding: 10rpx 20rpx 10rpx 0; display: flex; align-items: center; gap: 12rpx; border-bottom: 1rpx solid #eceef1; }
.field-row:last-child { border-bottom: none; }
.field-label-wrap { width: 170rpx; display: flex; align-items: center; gap: 12rpx; flex-shrink: 0; }
.field-label-wrap image { width: 30rpx; height: 30rpx; }
.field-label { color: #4d535c; font-size: var(--font-body, 24rpx); }
.field-input { flex: 1; min-width: 0; min-height: 70rpx; color: #17191c; font-size: var(--font-body, 25rpx); text-align: right; }
.small-action { min-height: 56rpx; margin: 0; padding: 0 10rpx; border: none; border-radius: 10rpx; background: #eceef1; color: #555b64; font-size: var(--font-meta, 21rpx); line-height: 1.2; }
.connection-actions { margin: 16rpx 20rpx 0; display: grid; grid-template-columns: 2fr 1fr 1fr; gap: 12rpx; }
.connection-actions button { min-width: 0; padding: 0 12rpx; }
.diagnostic-row { min-height: 104rpx; padding: 16rpx 24rpx; display: flex; align-items: center; gap: 16rpx; }
.diagnostic-row > view { flex: 1; min-width: 0; }
.diagnostic-title { display: block; font-size: var(--font-title, 27rpx); font-weight: 650; }
.diagnostic-subtitle { display: block; margin-top: 5rpx; color: #777d86; font-size: var(--font-meta, 22rpx); }
.diagnostic-button { min-height: 64rpx; margin: 0; padding: 0 18rpx; border: none; border-radius: 12rpx; background: #eceef1; color: #333840; font-size: var(--font-body, 23rpx); line-height: 1.2; }
.diagnosis-result { margin: 0 24rpx 20rpx; padding: 18rpx; border-radius: 14rpx; background: #f1f3f5; }
.diagnosis-title { display: block; font-size: var(--font-body, 25rpx); font-weight: 680; }
.diagnosis-detail { display: block; margin-top: 6rpx; color: #686e77; font-size: var(--font-meta, 23rpx); line-height: 1.5; }
.advanced-toggle { width: 100%; min-height: var(--app-control-height, 92rpx); margin: 0; padding: 0 24rpx; display: flex; align-items: center; justify-content: space-between; border: none; border-radius: 0; background: #fff; color: #32373e; font-size: var(--font-body, 25rpx); text-align: left; }
.advanced-toggle image { width: 30rpx; height: 30rpx; transition: transform .18s ease; }
.advanced-toggle image.is-open { transform: rotate(180deg); }
.advanced-content { padding: 0 20rpx 20rpx; background: #fff; border-bottom: 1rpx solid #e7e9ed; }
.full-button { width: 100%; }
.generated-token { margin-top: 14rpx; padding: 18rpx; border-radius: 14rpx; background: #f1f3f5; }
.generated-label { display: block; color: #777d86; font-size: var(--font-meta, 21rpx); }
.generated-value { display: block; margin-top: 6rpx; color: #22262b; font-size: var(--font-meta, 23rpx); word-break: break-all; }
.protocol-list { margin-top: 18rpx; }
.protocol-list view { min-height: 64rpx; display: flex; align-items: center; justify-content: space-between; border-top: 1rpx solid #eceef1; color: #717780; font-size: var(--font-meta, 23rpx); }
.protocol-list view text:last-child { color: #333840; font-weight: 600; text-align: right; }
.scroll-spacer { height: 44rpx; }
</style>
